; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
; board_build.mcu = rp2350-arm-s
; board_build.mcu = rp2350-riscv
board_build.mcu = rp2040
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
debug_init_break = tbreak setup
monitor_port = /dev/serial/by-id/usb-Raspberry_Pi_Debug_Probe__CMSIS-DAP__E664A836A33D5E35-if01
monitor_speed = 115200
; build_type = debug
build_flags =
    -D PICO_WIFI_ENABLED
    -D GPIO_HI_PRIORITY_IRQ_FALLBACK_CORE=1
    ; -D DEBUG_RP2040_PORT=Serial1
    ; -D DEBUG_RP2040_WIRE
    ; -D DEBUG_RP2040_SPI
    ; -D DEBUG_RP2040_CORE
    ; -D DEBUG_RP2040_WIFI
    ; -fstack-protector
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_IPV6
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS

    -D USER_SETUP_LOADED=1
    -D GC9A01_DRIVER=1
    -D RP2040_DMA=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=19
    -D TFT_SCLK=18
    -D TFT_CS=17
    -D TFT_DC=13
    -D TFT_RST=12
    -D SPI_FREQUENCY=40000000

    ; -g3
    ; -ggdb
    ; -O0
    ; -O3
    ; -mfloat-abi=hard -mfpu=fpv5-sp-d16
    ; -D PICO_FLOAT_SUPPORT_ROM_V2=1
board_build.filesystem = littlefs
; board_build.f_cpu = 200000000L
board_build.filesystem_size = 1m

lib_deps =
    bodmer/TFT_eSPI@^2.5.43